# Generated by Django 4.2.5 on 2023-10-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(default="Intrument", max_length=64),
        ),
    ]
