# Generated by Django 4.2.5 on 2023-11-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_itemcarrinho"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
